@baseUrl = http://localhost:3000

### MESSAGES ###

### findAll messages
GET {{baseUrl}}/messages
?limit=10
&offset=0
Authorization: Bearer 123456


### findById message
GET {{baseUrl}}/messages/30

### create message
POST {{baseUrl}}/messages
Content-Type: application/json

  {
    "text": "go to EUA!",
    "fromId": 14,
    "toId": 13
  }

### update message
PATCH {{baseUrl}}/messages/30
Content-Type: application/json

  {
    "text": "I like coca cola!!!",
    "read": true
  }

### deleteById message
DELETE  {{baseUrl}}/messages/17


### USERS ###

### findAll users
GET {{baseUrl}}/users
?limit=10
&offset=0

### findById user
GET {{baseUrl}}/users/15

### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Marley",
  "email": "marley@gmail.com",
  "password": "123456"
}

### update user
PATCH {{baseUrl}}/users/17
Content-Type: application/json

  {
    "name": "Marley",
    "password": "123456"
  }

### deleteById user
DELETE  {{baseUrl}}/users/17