@baseUrl = http://localhost:3000

@authToken = {{authenticate.response.body.accessToken}}

@refreshToken = {{authenticate.response.body.refreshToken}}


### MESSAGES ###

### findAll messages
GET {{baseUrl}}/messages
?limit=10
&offset=0


### findById message
GET {{baseUrl}}/messages/51

### create message
POST {{baseUrl}}/messages
Authorization: Bearer {{authToken}}
Content-Type: application/json

  {
    "text": "go to SASUKkpokkpkpokokE!",
    "toId": 13
  }

### update message
PATCH {{baseUrl}}/messages/53
Authorization: Bearer {{authToken}}
Content-Type: application/json

  {
    "text": "BATMANllllllllllllllll!!!",
    "read": false
  }

### deleteById message
DELETE  {{baseUrl}}/messages/53
Authorization: Bearer {{authToken}}


### USERS ###

### findAll users
GET {{baseUrl}}/users
?limit=10
&offset=0
Authorization: Bearer {{authToken}}

### findById user
GET {{baseUrl}}/users/29
Authorization: Bearer {{authToken}}


### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Pitina", 
  "email": "pitina@gmail.com", 
  "password": "123456"
}

### update user
PATCH {{baseUrl}}/users/29
Authorization: Bearer {{authToken}}
Content-Type: application/json

  {
    "name": "gata"
  }

### deleteById user
DELETE  {{baseUrl}}/users/29
Authorization: Bearer {{authToken}}



### AUTH ###

### authentication
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "tati@gmail.com",
  "password": "123456"
}

### re-authentication
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### UPLOAD IMAGES ###

POST {{baseUrl}}/users/upload-picture
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimitedHttp

------BoundaryDelimitedHttp
Content-Disposition: form-data; name="file"; filename="space002.jpg"
Content-Type: image/jpg

< ./images/space002.jpg
------BoundaryDelimitedHttp--


### GET PICTURES ###
GET {{baseUrl}}/pictures/24.jpg
